- name: Configure App # <-- Словесное описание сценария (name)
  hosts: app # <-- Для каких хостов будут выполняться описанные ниже таски (hosts)
  become: true
  roles:
    - app
#    - jdauphant.nginx

